camera:
  device: "/dev/video0"  # Kullanılacak kamera cihaz yolu
  width: 1920  # Görüntü genişliği (piksel)
  height: 1080  # Görüntü yüksekliği (piksel)
  frame_rate: 30  # Kare hızı (FPS)
  bayer_format: "rggb"  # Bayer formatı (rggb, bggr, grbg, gbrg)

controls:
  brightness: 128  # Parlaklık seviyesi (Min: 0, Max: 255)
  red_balance: 100  # Kırmızı beyaz dengesi (Min: 0, Max: 400)
  blue_balance: 100  # Mavi beyaz dengesi (Min: 0, Max: 400)
  gain: 75  # Kazanç değeri (ISO artırımı) (Min: 0, Max: 100)
  white_balance_temperature: 6000  # Beyaz dengesi sıcaklığı (Min: 2000, Max: 15000)
  white_balance_auto: 0  # Otomatik beyaz dengesi (0: Kapalı, 1: Açık)
  auto_exposure: 1  # Otomatik pozlama (0: Kapalı, 1: Açık)
  exposure_absolute: 100  # Mutlak pozlama süresi (ms cinsinden) (Min: 1, Max: 10000)
  exposure_time_us: 100  # Pozlama süresi (mikrosaniye) (Min: 10, Max: 1000000)
  auto_shutter: 1  # Otomatik perde hızı (0: Kapalı, 1: Açık)
  auto_exposure_reference: 150  # Otomatik pozlama referans seviyesi (Min: 0, Max: 255)
  gain_auto: 0  # Otomatik kazanç (0: Kapalı, 1: Açık)
  trigger_mode: 0  # Harici tetikleme modu (0: Kapalı, 1: Açık)
  strobe_enable: 0  # Strobe sinyali etkinleştirme (0: Kapalı, 1: Açık)
  flip_horizontal: 0  # Yatay çevirme (0: Kapalı, 1: Açık)
  flip_vertical: 0  # Dikey çevirme (0: Kapalı, 1: Açık)
  tone_mapping: 1  # Parlaklık azaltma (0: Kapalı, 1: Açık)
  exposure_auto_upper_limit_auto: 0   # Üst pozlama sınırı otomatik (0: Kapalı, 1: Açık)
  exposure_auto_lower_limit_us: 100  # Alt pozlama sınırı (mikrosaniye) (Min: 10, Max: 1000000)
  exposure_auto_upper_limit_us: 10000  # Üst pozlama sınırı (mikrosaniye) (Min: 10, Max: 1000000)
  override_scanning_mode: 1  # Tarama modu geçersiz kılma (0: Kapalı, 1: Açık)
  auto_functions_roi_preset: 1  # Otomatik fonksiyonlar için ROI ön ayarı (Min: 0, Max: 4)
  gain_auto_lower_limit: 0  # Otomatik kazanç alt sınırı (Min: 0, Max: 100)
  gain_auto_upper_limit: 100  # Otomatik kazanç üst sınırı (Min: 0, Max: 100)
  trigger_global_reset_release: 0  # Global reset tetikleme (0: Kapalı, 1: Açık)
  scanning_mode_selector: 1  # Tarama modu seçici (Min: 0, Max: 3)
  scanning_mode_identifier: 1  # Tarama modu tanımlayıcı (Min: 0, Max: 3)
  scanning_mode_scale_horizontal: 1  # Yatay ölçeklendirme faktörü (Min: 1, Max: 4)
  scanning_mode_scale_vertical: 1  # Dikey ölçeklendirme faktörü (Min: 1, Max: 4)
  scanning_mode_binning_h: 1  # Yatay binning faktörü (Min: 1, Max: 4)
  scanning_mode_binning_v: 1  # Dikey binning faktörü (Min: 1, Max: 4)
  scanning_mode_skipping_h: 1  # Yatay atlama faktörü (Min: 1, Max: 4)
  scanning_mode_skipping_v: 1  # Dikey atlama faktörü (Min: 1, Max: 4)
  scanning_mode_flags: 0  # Tarama modu bayrakları (Min: 0, Max: 255)
  trigger_delay_100ns: 100  # Tetikleme gecikmesi (100ns biriminde) (Min: 0, Max: 1000000)